name: Docker image build and push
on: 
  push:
    branches:
    - testing

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERSION: latest

    steps:
    - uses: actions/checkout@v1

    - name: Get latest Loki release
      run: |
        export LOKI_LATEST=$(curl -s "https://api.github.com/repos/grafana/loki/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
        echo "::set-env name=VERSION::$LOKI_LATEST"
      shell: bash
    
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin

    - name: Build the latest Docker image
      run: docker build --build-arg VERSION=master -t loki:latest .
      if: success() && env.VERSION == 'latest'
    
    - name: Build the Docker image
      run: docker build -t --build-arg VERSION=$VERSION loki:$VERSION .
      if: success() && env.VERSION != 'latest'