name: Docker image build and push

on: 
  push:
    branches:
      - master
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Get latest Loki release
      run: |
        export LOKI_LATEST=$(curl -s "https://api.github.com/repos/grafana/loki/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
        echo "VERSION=$LOKI_LATEST" >> ${GITHUB_ENV}
      shell: bash
    
    - name: Always build the latest Docker image
      run: docker build --build-arg VERSION=master -t loki:latest .

    - name: Compare release with already pushed version
      run: |
        export LOKI_AVAIL=$(curl -s "https://hub.docker.com/v2/repositories/urfin78/loki-i386/tags/"|grep -Po "$VERSION")
        echo "AVAIL=$LOKI_AVAIL" >> ${GITHUB_ENV}
      if: success()

    - name: Build the Docker image for new version
      run: docker build --build-arg VERSION=$VERSION -t loki:$VERSION .
      if: success() && env.VERSION != env.AVAIL
    
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin

    - name: Tag the latest Docker image
      run: docker tag loki:latest docker.pkg.github.com/urfin78/loki-docker-i386/loki:latest
      if: success()

    - name: Push the latest image to GPR
      run: docker push docker.pkg.github.com/urfin78/loki-docker-i386/loki:latest
      if: success()

    - name: Tag the new version Docker image
      run: docker tag loki:$VERSION docker.pkg.github.com/urfin78/loki-docker-i386/loki:$VERSION
      if: success() && env.VERSION != env.AVAIL

    - name: Push the new version image to GPR
      run: docker push docker.pkg.github.com/urfin78/loki-docker-i386/loki:$VERSION
      if: success() && env.VERSION != env.AVAIL

    - name: Logout from GitHub Registry
      run: docker logout docker.pkg.github.com

    - name: Login to Dockerhub Registry
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      if: success()
    
    - name: Tag the latest Docker image
      run: docker tag loki:latest urfin78/loki-i386:latest
      if: success()
   
    - name: Push the latest image to Dockerhub
      run: docker push urfin78/loki-i386:latest
      if: success()
      
    - name: Tag the new version Docker image
      run: docker tag loki:$VERSION urfin78/loki-i386:$VERSION
      if: success() && env.VERSION != env.AVAIL
   
    - name: Push the new version image to Dockerhub
      run: docker push urfin78/loki-i386:$VERSION
      if: success() && env.VERSION != env.AVAIL
    
    - name: Logout from Dockerhub Registry
      run: docker logout
