name: Docker image build and push
on: 
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.actor }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t loki:latest .
      
    - name: Tag the Docker image
      run: docker tag loki:latest docker.pkg.github.com/urfin78/loki-docker-i386/loki:latest

    - name: Push the image to GPR
      run: docker push docker.pkg.github.com/urfin78/loki-docker-i386/loki:latest .
