name: GHCR API Test

on: 
  push:
    branches:
      - 'integrate-ghcr'
    
jobs:
  api:
    name: API
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get package versions
      id: get_versions
      uses: octokit/request-action@v2.x
      with:
        route: GET /users/{owner}/packages/container/loki/versions
        owner: ${{ github.repository_owner }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo available versions: ${{ steps.get_versions.outputs.data }}"